import type { Metadata } from "next";
import { Exo_2, Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
   weight: "400",
   variable: "--font-roboto",
   subsets: ["latin-ext"],
});

const exo_2 = Exo_2({
   variable: "--font-exo_2",
   subsets: ["latin-ext"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${roboto.variable} ${exo_2.variable}`}>{children}</body>
      </html>
   );
}
